service: serverless-bolt-js
frameworkVersion: "3.15.0"
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: slack/events
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
