service: athena-leave-bot
frameworkVersion: "3.15.0"
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: post
  cron:
    handler: src/cron.startOfWeek
    events:
      # 10pm every Sunday UTC (8am every Monday AEST) 
      - schedule: cron(0 22 ? * SUN *)

  cronToday:
    handler: src/cron.today
    events:
      # 10pm every sunday-thursday UTC (8am every weekday AEST) 
      - schedule: cron(0 22 ? * SUN-THU *)
      # For testing
      # - schedule: cron(30 * * * ? *)

resources:
  Resources:
    athenaLeaveTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: athena-leave
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-esbuild
  - serverless-offline
